apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base

## FIXME: Temporary until nb-controller PR is merged into v1.7
images:
- name: quay.io/opendatahub/odh-notebook-controller
  newName: quay.io/maistra-dev/odh-notebook-controller
  newTag: service-mesh-integration
